### ISSUE TITLE
TypeScript build fails

### ISSUE THREAD

**Issue by Fumiruu** [CapOliveiraBr/yutub#10]
Hello

There is a misspell in the typing that prevents the build.

```
node_modules/yutub/src/index.d.ts:65:9 - error TS2304: Cannot find name 'strin'.

65     id: strin;
```

**Comment by CapOliveiraBr** [comment]
Hello, thanks to report! In the next update it will be corrected. 😅

**Comment by CapOliveiraBr** [comment]
F










i



x

**Comment by CapOliveiraBr** [comment]
Fixed! See: https://github.com/CapOliveiraBr/yutub/releases/tag/1.1.5
